# 📅 Настройки напоминаний
reminders:
  one_day: 86400     # За 1 день (в секундах)
  one_hour: 3600     # За 1 час
  fifteen_minutes: 900  # За 15 минут
  one_week: 604800   # За 1 неделю

# 📂 База данных
database:
  type: sqlite       # Можно заменить на postgresql, если нужно
  path: "data/tasks.db"  # Файл базы SQLite

# 🌍 Локализация
localization:
  default_language: "ru"
  available_languages: ["ru", "en"]

# ⏳ Настройки фоновых задач
scheduler:
  interval: 60  # Запуск фоновой проверки задач каждые 60 секунд

# 🔌 Интеграции (Google Calendar, если добавишь)
integrations:
  google_calendar: false  # Пока отключено, но можно включить позже
